### Get Jobs
GET http://localhost:4444/auth/signin

### Create Job
POST http://localhost:4444/auth/signin
content-type: application/json

{
    "company": "Temirtau23",
    "geography": "Budju, USA",
    "jobLink": "https://devrelcareers.com/job/8",
    "title": "Full Stack"
}

### Put Job
PUT http://localhost:4444/auth/
content-type: application/json

{
    "company": "ITVDN33"
}

### Delete Job
DELETE http://localhost:4444/auth/
content-type: application/json